### ISSUE TITLE
xAOD migration: Taus

### ISSUE THREAD

**Issue by amete** [gerbaudo/SusyCommon#41]
Sorry if there is already an open issue on this, but I didn't see one. If my recollection is correct @suneetu you were looking into this. From my notes w/ my discussion w/ @ataffard I see there are a few things that need to be implemented on that tau side, including the truth info etc. Where are we on these, please?

-s

**Comment by gerbaudo** [comment]
implemented by @suneetu in gerbudo/SusyCommon#50
